from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os

def create_clean_pdf(filename, content, i):
    """Creates a basic, text-only PDF using reportlab."""
    try:
        c = canvas.Canvas(filename, pagesize=letter)
        c.drawString(72, 800, f"--- Test Document #{i+1} ---")
        c.drawString(72, 780, f"Filename: {filename}")
        c.drawString(72, 760, "This is a clean, virus-free PDF generated by a standard Python library.")
        
        # Add the specific content provided
        y_position = 730
        for line in content.split('\n'):
            c.drawString(72, y_position, line)
            y_position -= 15
            if y_position < 50: # Avoid going off the page
                break
                
        c.save()
        print(f"Successfully created: {filename}")
        return True
    except Exception as e:
        print(f"Error creating PDF {filename}: {e}")
        return False

# Define the 5 PDFs to create
pdf_specs = [
    ("test_pdf_1_simple.pdf", "Content for testing basic file upload and scanning."),
    ("test_pdf_2_report.pdf", "Document is a summary of clean findings. Contains no suspicious keywords."),
    ("test_pdf_3_low_risk.pdf", "This document tests the AI's ability to classify 'Low' risk. Static scan should show no findings."),
    ("test_pdf_4_size_test.pdf", "A slightly larger document to test file handling."),
    ("test_pdf_5_final_test.pdf", "Final clean test document.")
]

# Ensure the script runs from the directory you want the PDFs in
if __name__ == "__main__":
    for i, (filename, content) in enumerate(pdf_specs):
        create_clean_pdf(filename, content, i)

    print("\n--- Generation Complete ---")
    print("You can now use these 5 PDFs to test the 'Low' risk path of your CyberDoc Scanner.")
